<?php

namespace Prateek\Webhooks\Http\Controllers;

use Illuminate\Http\Request;
use Prateek\Webhooks\Facades\payloadParser;
use Prateek\Webhooks\Models\EmailStats;

class emailStatistics extends payloadParser {

    function __construct() {
    }

    static function validateData() {

        $rules = [
            "lastEmailSent",
            "lastEmailSentAt",
            "backlogEmails"
        ];

        parent::validateData($rules); // TODO: Change the autogenerated stub
    }

    function insertData() {
        parent::insertData(); // TODO: Change the autogenerated stub
    }

    public function hookData(Request $request) {
        print_r($request -> json());
        //insert data from the call.
        //$email_stats = new EmailStats();
        //$email_stats = $request -> input('')
    }
}
